CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS country (
  country_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS town (
  town_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  town_name VARCHAR NOT NULL,
  country_id INT NOT NULL REFERENCES country(country_id)
);

CREATE TABLE IF NOT EXISTS genres (
  genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genre_name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR NOT NULL UNIQUE,
  password_hash VARCHAR NOT NULL,
  username VARCHAR NOT NULL,
  role VARCHAR NOT NULL,
  description VARCHAR,
  avatar_url VARCHAR,
  latitude NUMERIC NOT NULL,
  longitude NUMERIC NOT NULL,
  created_at DATE NOT NULL,
  town_id INT NOT NULL DEFAULT 1 REFERENCES town(town_id)
);

CREATE TABLE IF NOT EXISTS media (
  media_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  href VARCHAR NOT NULL,
  user_id INT NOT NULL REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS games (
  game_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_name VARCHAR NOT NULL,
  publisher VARCHAR NOT NULL,
  max_min_players VARCHAR NOT NULL,
  avg_play_time INT NOT NULL,
  complexity INT NOT NULL,
  year_published INT NOT NULL,
  media_id INT REFERENCES media(media_id)
);

CREATE TABLE IF NOT EXISTS listing (
  listing_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  condition VARCHAR NOT NULL,
  is_active BOOLEAN NOT NULL,
  created_at DATE NOT NULL,
  description VARCHAR,
  user_id INT NOT NULL REFERENCES users(user_id),
  game_id INT NOT NULL REFERENCES games(game_id),
  media_id INT NOT NULL REFERENCES media(media_id)
);

CREATE TABLE IF NOT EXISTS offers (
  offer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offer_status INT NOT NULL,
  message VARCHAR,
  created_at DATE NOT NULL,
  from_user_id INT NOT NULL REFERENCES users(user_id),
  to_user_id INT NOT NULL REFERENCES users(user_id),
  target_listing_id INT NOT NULL REFERENCES listing(listing_id)
);

CREATE TABLE IF NOT EXISTS trade (
  trade_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agreed_at DATE NOT NULL,
  trade_status INT NOT NULL,
  rating_from_buyer INT NOT NULL,
  rating_from_seller INT NOT NULL,
  offer_id INT NOT NULL REFERENCES offers(offer_id)
);

CREATE TABLE IF NOT EXISTS notifications (
  notification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR NOT NULL,
  payload NUMERIC NOT NULL,
  is_read BOOLEAN NOT NULL,
  created_at DATE NOT NULL,
  user_id INT NOT NULL REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS whishes_for (
  user_id INT NOT NULL REFERENCES users(user_id),
  game_id INT NOT NULL REFERENCES games(game_id),
  PRIMARY KEY (user_id, game_id)
);

CREATE TABLE IF NOT EXISTS is_genre (
  game_id INT NOT NULL REFERENCES games(game_id),
  genre_id INT NOT NULL REFERENCES genres(genre_id),
  PRIMARY KEY (game_id, genre_id)
);

CREATE TABLE IF NOT EXISTS is_intrested (
  user_id INT NOT NULL REFERENCES users(user_id),
  genre_id INT NOT NULL REFERENCES genres(genre_id),
  PRIMARY KEY (user_id, genre_id)
);

CREATE TABLE IF NOT EXISTS offer_items (
  quantity INT NOT NULL,
  offer_id INT NOT NULL REFERENCES offers(offer_id),
  listing_id INT NOT NULL REFERENCES listing(listing_id),
  PRIMARY KEY (offer_id, listing_id)
);

INSERT INTO country (country_id, country_name)
VALUES (1, 'Unknown')
ON CONFLICT (country_id) DO NOTHING;

INSERT INTO town (town_id, town_name, country_id)
VALUES (1, 'Unknown', 1)
ON CONFLICT (town_id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('country', 'country_id'),
              COALESCE((SELECT MAX(country_id) FROM country), 1),
              true);

SELECT setval(pg_get_serial_sequence('town', 'town_id'),
              COALESCE((SELECT MAX(town_id) FROM town), 1),
              true);
