spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/appdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:app}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.check_nullability=false

logging.level.org.springframework.security=INFO


spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile,openid

spring.jpa.properties.hibernate.show_sql=false


server.servlet.session.cookie.same-site=Lax
server.servlet.session.cookie.secure=false

server.frontend=${SERVER_FRONTEND:http://localhost:5173}
server.frontend.allowed-origins=${SERVER_FRONTEND_ALLOWED_ORIGINS:http://localhost:5173}
