spring.application.name=backend

logging.level.org.springframework.security=TRACE

#google login
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile,openid

#database connection
spring.datasource.url=jdbc:postgresql://dpg-d5en4824d50c73c7dvn0-a.frankfurt-postgres.render.com:5432/playtrade_18mp?sslmode=require
spring.datasource.username=playuser
spring.datasource.password=${POSTGRE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.forward-headers-strategy=framework

server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=true



server.frontend=https://ststiroporwebpl.z36.web.core.windows.net
