spring.application.name=backend

logging.level.org.springframework.security=INFO

#google login
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile,openid

#database connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d5en4824d50c73c7dvn0-a.frankfurt-postgres.render.com:5432/playtrade_18mp?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:playuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRE_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=stiropor.playtrade@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.forward-headers-strategy=framework

server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=true

server.frontend=${SERVER_FRONTEND:https://ststiroporwebpl.z36.web.core.windows.net}
server.frontend.allowed-origins=${SERVER_FRONTEND_ALLOWED_ORIGINS:https://ststiroporwebpl.z36.web.core.windows.net,http://localhost:5173}
